const articles = [
  {
    "id": "art-001",
    "slug": "cuando-habla-la-luz",
    "pillar": "portada",
    "subcategory": "Fotografía",
    "category": "PHotoESPAÑA 2025",
    "tag": "Fotografía",
    "title": "Cuando habla la luz",
    "subtitle": "La mirada insobornable de Graciela Iturbide llega a Madrid tras recibir el Premio Princesa de Asturias de las Artes.",
    "body": "El arte tiene la capacidad de revelar lo invisible: la dignidad, el dolor, la belleza y el espíritu de un país. En nuestras salas, las imágenes de Graciela Iturbide no solo se contemplaron, se reconocieron como parte de nuestro imaginario común.\n\nEsta exposición representó su primera gran muestra tras ser galardonada con el Premio Princesa de Asturias de las Artes 2025. Junto a los proyectos de Lourdes Grobet y Alinka Echeverría, ampliamos la conversación sobre memoria, cuerpo y territorio, demostrando que la cultura mexicana contemporánea no busca el exotismo, sino la universalidad.\n\n\"Me encanta Casa de México. Me parece maravilloso que dé a conocer nuestro país en España y a todas las personas del resto del mundo. La relación que tiene México con España es muy importante por el mestizaje.\" — Graciela Iturbide\n\nLa muestra fue comisariada por Juan Rafael Coronel Rivera en colaboración con Fomento Cultural Banamex. Cada sala trazó un recorrido por la mirada de la artista: las mujeres de Juchitán, la frontera, Oaxaca. Imágenes que convierten lo cotidiano en arte y lo íntimo en experiencia colectiva.",
    "author": "Ximena Caraza Campos",
    "institution": "Fundación Casa de México en España",
    "imageKey": "iturbide-iguanas",
    "readTime": "06 MIN",
    "accentColor": "magenta",
    "date": "Marzo 2026",
    "type": "Fotografía",
    "featured": true
  },
  {
    "id": "art-008",
    "slug": "becas-casa-de-mexico-2025",
    "pillar": "portada",
    "subcategory": "Formación",
    "category": "Formación y Talento",
    "tag": "Becas",
    "title": "Sembrar futuro",
    "subtitle": "El Programa de Becas triplicó solicitudes y otorgó un 260% más de becas que en 2024. Prado, Thyssen, Teatro Real: las instituciones más exigentes de España.",
    "body": "El Programa de Becas Fundación Casa de México en España tiene como objetivo consolidarse como un detonador de oportunidades para el talento mexicano. En 2025, el crecimiento fue notable: la convocatoria triplicó el número de solicitudes, atrayendo perfiles de 31 estados de la República. Se otorgó un 260% más de becas que el año anterior.\n\nLa modalidad de Formación Académica colabora con las universidades más reconocidas de España: Complutense, Navarra, Carlos III, IE University, ECAM, MADS. Jóvenes mexicanos formándose en las mejores instituciones de un continente distinto. No como turistas culturales: como profesionales en formación.\n\nLa nueva modalidad Desarrollo de Talento fue aún más exigente. Profesionales mexicanos del ámbito cultural con experiencia comprobada, colaborando con el Museo Nacional del Prado, el Thyssen-Bornemisza, el Teatro Real, el MACBA y el Guggenheim Bilbao.\n\n\"El Programa de Becas se ha convertido en un puente sólido entre los dos países, no solo en términos académicos, sino también como plataforma para la creación de redes profesionales y culturales.\"\n\nEste año también comenzó el Programa Mexicouture: tres diseñadoras de moda —Denisse Kuri, Concepción Orvañanos y Arizbeth Fierro— realizaron una estancia en Madrid en el ecosistema creativo español.",
    "author": "Luis Fernando Garza Bravo",
    "institution": "Casa de México",
    "imageKey": "culture",
    "readTime": "06 MIN",
    "accentColor": "emerald",
    "date": "2025",
    "type": "Formación",
    "featured": false
  },
  {
    "id": "art-002",
    "slug": "la-mitad-del-mundo",
    "pillar": "cultura",
    "subcategory": "Artes Visuales",
    "category": "Exposición INAH",
    "tag": "Arte Mesoamericano",
    "title": "La mitad del mundo",
    "subtitle": "La mujer en el México indígena: un centenar de piezas mesoamericanas dialogan con el presente en Madrid.",
    "body": "La exposición La mitad del mundo. La mujer en el México indígena. El ámbito divino no fue simplemente una muestra de piezas excepcionales, sino un relato vivo sobre nuestras raíces, nuestras tradiciones y, especialmente, sobre la mujer como portadora de memoria, conocimiento y continuidad cultural.\n\nOrganizada junto con el Instituto Nacional de Antropología e Historia y el Gobierno de México, reunimos casi un centenar de piezas provenientes de veinticuatro museos de diferentes regiones de México. La curadora Karina Romero Blanco trazó un recorrido que revelaba la presencia poderosa de lo femenino en la cosmovisión mesoamericana: como madre, diosa, energía vital o cueva primigenia.\n\nLa Venus de Tamtoc —monumento 33, cultura tének, 150 d. C.— detuvo el tiempo en una sala. A su lado, vasijas rituales para pulque de la diosa Mayahuel y tablas nierika wixárikas del siglo XXI completaron un diálogo atemporal entre tradición y mirada contemporánea.\n\nEsta exposición fue la más relevante de arte mesoamericano organizada en España hasta la fecha. Formó parte de la conmemoración del Año de la Mujer Indígena, con sedes en el Thyssen-Bornemisza, el Museo Arqueológico Nacional y el Instituto Cervantes.",
    "author": "Karina Romero Blanco",
    "institution": "Casa de México / INAH",
    "imageKey": "arte-mesoamerica",
    "readTime": "08 MIN",
    "accentColor": "ochre",
    "date": "2025",
    "type": "Artes Visuales",
    "featured": false
  },
  {
    "id": "art-005",
    "slug": "eramos-felices",
    "pillar": "cultura",
    "subcategory": "Artes Visuales",
    "category": "Arte Contemporáneo",
    "tag": "Coleccionismo",
    "title": "Éramos felices y no lo sabíamos",
    "subtitle": "La Colección Jumex replantea la mirada sobre el arte mexicano de los noventa en el contexto europeo.",
    "body": "Comisariada por Ixel Rion Lora, la exposición Éramos felices y no lo sabíamos reunió piezas de veintiocho artistas en video, instalación, fotografía y escultura realizadas entre mediados de los años noventa y principios de la década del 2000.\n\nAle de la Puente propuso Turbulencias del vacío: dos alfombras, un haz de luz y el sonido del clarinete pulsando al ritmo del vacío y su turbulencia. Minerva Cuevas exhibió Target Shell. Jose Dávila, una pieza sin título que habla del peso de lo que no se nombra.\n\nLa muestra mostró un recorrido por la memoria visual de toda una generación, un periodo de búsqueda y experimentación en el que la juventud tomó riesgos y generó nuevas formas de expresión. Arte mexicano que no se exhibe como rareza, sino como parte activa del diálogo cultural europeo.\n\n\"Carlos Cuarón dijo de esta casa: nos ayuda a difundir nuestro trabajo y a que lo conozcan bien en España. Somos hermanos.\"",
    "author": "Ixel Rion Lora",
    "institution": "Casa de México / Colección Jumex",
    "imageKey": "arte-contemporaneo",
    "readTime": "05 MIN",
    "accentColor": "primary",
    "date": "2025",
    "type": "Artes Visuales",
    "featured": false
  },
  {
    "id": "art-004",
    "slug": "maestria-popotillo",
    "pillar": "cultura",
    "subcategory": "Arte Popular",
    "category": "Arte Popular",
    "tag": "Hecho a Mano",
    "title": "Maestría en Popotillo",
    "subtitle": "Martha Patricia García Aguilar preserva la técnica ancestral del teñido con anilinas. Una pieza que es devoción y arte.",
    "body": "El Programa de Rescate y Fortalecimiento del Arte Popular Mexicano fue creado para preservar técnicas y procesos mediante el acompañamiento directo a maestras y maestros artesanos: un paso esencial para salvaguardar nuestro patrimonio vivo.\n\nMartha Patricia García Aguilar elabora sus piezas con popotillo teñido con anilinas. Sus obras de la Virgen de Guadalupe desdibujan la línea entre devoción popular y arte contemporáneo. Su trabajo es parte de las 1,500 piezas que conforman la colección más completa de arte popular mexicano fuera de México.\n\nLa tienda Hecho a Mano celebró dos ediciones en 2025 —primavera e invierno— con más de 3,500 piezas procedentes de Tlaxcala, Hidalgo, Puebla, Ciudad de México, Querétaro, Michoacán, Guanajuato y Jalisco.\n\nLos 59 talleres acercaron alrededor de 1,200 personas a oficios tradicionales: teñido natural de lana, plata, tapetes de Huamantla, pepenado, tenango, cerámica artística, plumaria, repujado, cestería, chaquira wixárika, grabado y elaboración de velas artesanales.",
    "author": "Ximena López Ruiz",
    "institution": "Casa de México",
    "imageKey": "artesania-mexicana",
    "readTime": "05 MIN",
    "accentColor": "cobalt",
    "date": "2025",
    "type": "Arte Popular",
    "featured": false
  },
  {
    "id": "art-003",
    "slug": "sello-copil-guia",
    "pillar": "cultura",
    "subcategory": "Gastronomía",
    "category": "Guía Culinaria",
    "tag": "Gastronomía",
    "title": "Sello Copil",
    "subtitle": "El distintivo a la excelencia en la cocina mexicana en España reconoce ya a cerca de cien restaurantes en Madrid.",
    "body": "La gastronomía continuó siendo un eje esencial de las actividades de Casa de México. El Sello Copil, nuestro distintivo a la excelencia en la cocina mexicana en España, reconoce ya a cerca de cien restaurantes, afianzándose como un referente que impulsa altos estándares y promueve una representación respetuosa de nuestras tradiciones culinarias.\n\nEl programa Entre Sabores reunió a chefs y cocineras tradicionales en talleres especializados. La segunda edición de México Enlaza – Destilados Mexicanos congregó cerca de medio millar de marcas. Chefmex Gourmet reunió a más de 600 profesionales del sector gastronómico.\n\n\"La cocina mexicana en España ha llegado para quedarse — no como curiosidad sino como parte viva del paisaje gastronómico europeo.\"\n\nEl maíz nixtamalizado, la vainilla de Papantla, el mole y los destilados artesanales de Querétaro son solo algunos de los protagonistas de esta revolución culinaria silenciosa. Una revolución que ocurre en los mejores restaurantes de Madrid, noche tras noche, plato a plato.",
    "author": "María Elena Torres Ramírez",
    "institution": "Casa de México",
    "imageKey": "gastronomia-fina",
    "readTime": "04 MIN",
    "accentColor": "emerald",
    "date": "2025–2026",
    "type": "Gastronomía",
    "featured": false
  },
  {
    "id": "art-009",
    "slug": "destilados-mexicanos-en-madrid",
    "pillar": "cultura",
    "subcategory": "Gastronomía",
    "category": "México Enlaza",
    "tag": "Destilados",
    "title": "El alma destilada de México",
    "subtitle": "Más de 450 marcas de mezcal, tequila y destilados artesanales toman Madrid. Una cata que es también una declaración de identidad.",
    "body": "La segunda edición de México Enlaza – Destilados Mexicanos reunió a más de 450 marcas, distribuidoras, comercializadores y profesionales del sector restaurantero. El propósito: fomentar la distribución, la comercialización y el consumo responsable de bebidas y destilados mexicanos en España.\n\nEntre aromas y matices, descubrimos la esencia de los destilados de México. No es solo comercio: es identidad en botella. El mezcal de Oaxaca lleva el humo de tierra quemada. El tequila de Jalisco lleva el agave azul y el sol seco. La Xalte de Colima —flor de sal artesanal— encontró su lugar en la coctelería de autor del chef Roberto Ruiz.\n\nLos destilados mexicanos han llegado a España después de décadas de confusión y olvido. Hoy, los mejores bares de Madrid sirven raicilla, sotol, tepache y kombucha de maíz morado. El sommelier español ya pronuncia \"Papalomex\" con reverencia.\n\nChefmex Gourmet completó el ecosistema: más de 600 profesionales del sector restaurantero explorando la diversidad y la riqueza de la cocina mexicana. No como exotismo. Como referencia.",
    "author": "Ricardo Salgado Peña",
    "institution": "Casa de México",
    "imageKey": "mezcal-destilados",
    "readTime": "05 MIN",
    "accentColor": "ochre",
    "date": "Octubre 2025",
    "type": "Gastronomía",
    "featured": false
  },
  {
    "id": "art-017",
    "slug": "cocinera-sabores-olvidados",
    "pillar": "cultura",
    "subcategory": "Gastronomía",
    "category": "Cocina Tradicional",
    "tag": "Gastronomía",
    "title": "La cocinera de los sabores olvidados",
    "subtitle": "Doña Esperanza Cruz cruzó el Atlántico con sus semillas de chile pasilla, su comal y cuarenta recetas que nadie más en Madrid sabe preparar.",
    "body": "Hay sabores que no caben en un menú de restaurante. Sabores que requieren tiempo, paciencia y el conocimiento que solo se transmite de mano a mano, de generación en generación. Doña Esperanza Cruz los tiene todos.\n\nLlegó a Madrid hace doce años desde Tlaxiaco, Oaxaca. Hoy, en un piso de Lavapiés, prepara cada semana un caldo de guías que sus vecinos madrileños llaman, sin entender del todo bien qué significa, \"el caldo de la abuela\". El caldo que huele a lluvia en tierra seca.\n\nSus manos conocen el tiempo exacto del mole negro: cuatro horas de comal, dos de molienda, una de espera. Sabe cuándo el chile pasilla está listo por el olor, no por el reloj. Sabe que la tortilla de maíz criollo bolita tiene que sonar diferente a la de maíz híbrido.\n\n\"Cocinar aquí es como hablar un idioma que nadie conoce. Pero cuando alguien lo prueba, lo entiende sin necesitar palabras.\" — Doña Esperanza Cruz\n\nEl chef Roberto Ruiz fue el primero en invitarla a cocinar en su restaurante certificado con el Sello Copil. Desde entonces, tres cocineras tradicionales más han encontrado espacio en cocinas de alta gama de Madrid. La cocina mexicana que más interesa a Europa no es la de las fusiones: es la que no se puede inventar.",
    "author": "Alejandra Mota Díaz",
    "institution": "XICO Madrid",
    "imageKey": "cocina-chef",
    "readTime": "06 MIN",
    "accentColor": "ochre",
    "date": "Marzo 2026",
    "type": "Gastronomía",
    "featured": false
  },
  {
    "id": "art-007",
    "slug": "coreograf-ia",
    "pillar": "cultura",
    "subcategory": "Artes Escénicas",
    "category": "Artes Escénicas",
    "tag": "Danza e IA",
    "title": "Coreograf-IA",
    "subtitle": "Victoria Riva Palacio combina movimiento humano e inteligencia artificial para recrear la magia y el canto de las aves.",
    "body": "La coreógrafa y bailarina Victoria Riva Palacio interpretó la performance Coreograf-IA en los espacios de Casa de México: una propuesta en la que el movimiento humano y la inteligencia artificial se combinaron para recrear la magia y el canto de las aves.\n\nEl resultado no fue tecnología disfrazada de arte. Fue arte que usó la tecnología como músculo. La diferencia es todo. El cuerpo de Palacio trazó trayectorias que la IA aprendía a reconocer, predecir y transformar. Un diálogo entre lo orgánico y lo computado que reveló algo inesperado: la IA no imita; desvía.\n\nEsta propuesta se inscribió dentro de la programación de artes escénicas de la Fundación, que durante 2025 albergó también bailes regionales del Ensamble Folclórico Mexicano, teatro de Jorge Volpi y Cristina Rivera Garza, y pastorelas navideñas coordinadas por Leopoldo Falcón.\n\nEn el ámbito de XICO, Coreograf-IA es un recordatorio: la IA no debe dominar la interfaz cultural. Debe mejorar relevancia y orden. El criterio humano sigue siendo el eje.",
    "author": "Ana Paula Oviedo Reyes",
    "institution": "Casa de México",
    "imageKey": "danza-contemporanea",
    "readTime": "05 MIN",
    "accentColor": "cobalt",
    "date": "2025",
    "type": "Artes Escénicas",
    "featured": false
  },
  {
    "id": "art-018",
    "slug": "folclore-no-es-nostalgia",
    "pillar": "cultura",
    "subcategory": "Artes Escénicas",
    "category": "Danza y Tradición",
    "tag": "Folclore Contemporáneo",
    "title": "Cuando el folclore no es nostalgia",
    "subtitle": "El Ensamble Folclórico Mexicano lleva años demostrando que la danza regional es arte contemporáneo cuando se ejecuta con rigor y honestidad.",
    "body": "Hay una trampa en la que cae fácilmente la danza folclórica mexicana fuera de México: volverse postal. Volverse el México que el turista quiere ver, no el México que existe. El Ensamble Folclórico Mexicano lleva años resistiendo esa trampa.\n\nSu presentación en Madrid fue una demostración de que la danza regional puede ser contemporánea sin perder su raíz. Los trajes de Jalisco, los sones de la Tierra Caliente de Guerrero y la danza de los Viejitos de Michoacán no fueron puestos en escena como museum pieces: fueron presentados como lo que son, prácticas vivas, cambiantes, disputadas.\n\nEl director Ernesto Fragoso habló antes de la función sobre la diferencia entre preservar y embalsamar. \"Preservar una danza significa seguir bailándola. Embalsamarla significa convertirla en espectáculo turístico.\" La diferencia, en escena, es inmediata. Se siente en los pies.\n\nEl público de Madrid respondió con una ovación que no tenía nada de condescendiente. Reconocieron arte, no curiosidad.",
    "author": "Ana Paula Oviedo Reyes",
    "institution": "XICO Madrid",
    "imageKey": "danza-escena",
    "readTime": "05 MIN",
    "accentColor": "cobalt",
    "date": "Enero 2026",
    "type": "Artes Escénicas",
    "featured": false
  },
  {
    "id": "art-019",
    "slug": "teatro-en-el-umbral",
    "pillar": "cultura",
    "subcategory": "Artes Escénicas",
    "category": "Teatro",
    "tag": "Teatro Mexicano",
    "title": "Teatro en el umbral",
    "subtitle": "Leopoldo Falcón lleva treinta años construyendo un teatro donde la tradición mexicana y la herencia española se reconocen sin necesitar traducción.",
    "body": "Leopoldo Falcón llegó a Madrid en 1994. Treinta años después, nadie en el teatro madrileño lo considera un extranjero. Tampoco lo considera completamente local. Vive en ese umbral que solo habitan quienes han decidido no elegir entre sus dos culturas.\n\nSu propuesta teatral parte siempre del texto, pero termina siempre en el cuerpo. Sus montajes de pastorela —la forma teatral más vieja del México colonial— han conseguido algo difícil: hacer que el público español encuentre en ellos algo familiar sin que el texto haya sido modificado para explicarles nada.\n\n\"El teatro que me interesa no necesita que el espectador sepa de dónde viene. Necesita que lo sienta. Y lo que se siente en una pastorela del siglo XVII o en una del XXI es lo mismo: la ansiedad de la espera, el asombro del nacimiento, la pregunta de si algo nuevo es posible.\"\n\nEn 2025, su Pastorela navideña reunió a más de 1,200 espectadores en Casa de México. Fue la función con mayor asistencia del año. Y no por nostalgia: por teatro.",
    "author": "Marcos Villanueva Soto",
    "institution": "Casa de México",
    "imageKey": "teatro-luces",
    "readTime": "06 MIN",
    "accentColor": "emerald",
    "date": "Diciembre 2025",
    "type": "Artes Escénicas",
    "featured": false
  },
  {
    "id": "art-020",
    "slug": "flor-garduno-cuerpo-es-jardin",
    "pillar": "cultura",
    "subcategory": "Fotografía",
    "category": "PHotoESPAÑA 2026",
    "tag": "Fotografía",
    "title": "Flor Garduño: el cuerpo es jardín",
    "subtitle": "La fotógrafa oaxaqueña llega a PHotoESPAÑA 2026 con una retrospectiva que reúne 35 años de imágenes donde naturaleza, cuerpo y rito son una sola cosa.",
    "body": "Flor Garduño nunca ha fotografiado lo que no conoce. Y lo que conoce —la mujer, la naturaleza, el ritual, la luz que entra oblicua en un cuarto de adobe— lo ha fotografiado con una fidelidad que roza lo sagrado.\n\nSu retrospectiva en PHotoESPAÑA 2026 es la primera vez que su obra completa se presenta en Europa. Ciento veinte imágenes en blanco y negro que recorren desde sus primeros trabajos en Guatemala en los años ochenta hasta sus series más recientes sobre los cuerpos y los jardines de Oaxaca.\n\nLo que más sorprende a quienes ven la retrospectiva es la constancia. En cuarenta años, la gramática visual de Garduño no ha cambiado: siempre esa luz lateral, esa composición que parece encontrada antes que construida, ese instante en que el cuerpo humano y la naturaleza dejan de ser dos cosas distintas.\n\n\"No soy fotógrafa de documentación. Soy fotógrafa de transformación. Lo que me interesa es el momento en que algo se convierte en otra cosa.\"\n\nLa retrospectiva incluye también una selección de sus fotografías de niños mayas de Chiapas, imágenes que forman parte de la colección permanente del MoMA de Nueva York y que nunca habían viajado a España.",
    "author": "Carmen Solís Jiménez",
    "institution": "XICO Madrid",
    "imageKey": "fotografia-retrato",
    "readTime": "07 MIN",
    "accentColor": "magenta",
    "date": "Mayo 2026",
    "type": "Fotografía",
    "featured": false
  },
  {
    "id": "art-021",
    "slug": "lourdes-grobet-lucha-libre",
    "pillar": "cultura",
    "subcategory": "Fotografía",
    "category": "Fotografía Documental",
    "tag": "Fotografía",
    "title": "Lourdes Grobet: la lucha libre como archivo",
    "subtitle": "Sus imágenes de la lucha libre mexicana son ahora canon de la fotografía latinoamericana. En Madrid se exhiben por primera vez en Europa.",
    "body": "Cuando Lourdes Grobet comenzó a fotografiar la lucha libre mexicana en los años setenta, nadie en el mundo del arte la tomó en serio. Era demasiado popular, demasiado kitsch, demasiado mexicana. Cincuenta años después, su archivo es estudiado en las mejores universidades de Estados Unidos y Europa como uno de los documentos más completos sobre la cultura popular urbana del siglo XX.\n\nLa exhibición en Casa de México presenta 80 imágenes seleccionadas del archivo de más de 10,000 fotografías que Grobet realizó entre 1975 y 1994. El Santo, El Perro Aguayo, Blue Demon: máscaras que son personajes, personajes que son mitología, mitología que es México.\n\nLo que convierte las fotografías de Grobet en arte y no solo en documento es la mirada. Ella no fotografió la lucha libre como espectáculo; la fotografió como ritual. Como el espacio donde la ciudad proyectaba sus miedos, sus deseos y su sentido del humor colectivo.\n\n\"La lucha libre es el teatro barroco de México. Tiene héroes, villanos, transformaciones y muerte fingida. Todo lo que el arte necesita.\"\n\nLa muestra incluye también testimonios en video de luchadores que conocieron a Grobet, y un catálogo con textos de Carlos Monsiváis y Susan Sontag.",
    "author": "Pablo Hernández Brito",
    "institution": "Casa de México",
    "imageKey": "camara-vintage",
    "readTime": "07 MIN",
    "accentColor": "cobalt",
    "date": "Abril 2026",
    "type": "Fotografía",
    "featured": false
  },
  {
    "id": "art-022",
    "slug": "alinka-echeverria-fronteras-visibles",
    "pillar": "cultura",
    "subcategory": "Fotografía",
    "category": "Fotografía Contemporánea",
    "tag": "Fotografía",
    "title": "Alinka Echeverría: fronteras visibles",
    "subtitle": "La fotógrafa mexicana radicada en Londres llega a Madrid con una serie sobre los cuerpos que cruzan océanos y la huella que ese cruce deja en la piel.",
    "body": "Alinka Echeverría nació en la Ciudad de México, estudió en Londres, ha vivido en Berlín, París y Lagos. Si alguien sabe lo que significa vivir con una frontera dentro, es ella.\n\nSu nueva serie, Entre dos mares, fue fotografiada en Madrid, Ciudad de México y la costa de Veracruz durante tres años. Las imágenes muestran cuerpos de mujeres mexicanas en España: cómo visten, cómo se mueven en el espacio, qué llevan consigo, qué han dejado atrás.\n\nEl trabajo de Echeverría no es sociología ilustrada. Es fotografía que parte de una pregunta: ¿cuánto del cuerpo cambia cuando cambia el país? La respuesta, en sus imágenes, no es nunca simple. Hay pérdida y hay ganancia. Hay adaptación que es traición y adaptación que es inteligencia.\n\n\"No fotografío la migración. Fotografío la supervivencia. Y la supervivencia tiene una estética particular: es práctica, es ingeniosa y es siempre más hermosa de lo que parece.\"\n\nLa exposición en Casa de México se presenta de forma simultánea con una muestra paralela en la Galería 0GRADOS de Ciudad de México.",
    "author": "Sofía Leal Noriega",
    "institution": "Casa de México",
    "imageKey": "ciudad-editorial",
    "readTime": "06 MIN",
    "accentColor": "magenta",
    "date": "Febrero 2026",
    "type": "Fotografía",
    "featured": false
  },
  {
    "id": "art-016",
    "slug": "cine-mexicano-en-europa",
    "pillar": "cultura",
    "subcategory": "Cine",
    "category": "Cine",
    "tag": "Cine",
    "title": "La pantalla como frontera",
    "subtitle": "Cinco directoras mexicanas cuyo cine llega a Europa este año y redefine lo que significa filmar desde el margen.",
    "body": "Hay un cine mexicano que no llega a los multiplex pero que transforma festivales. Este año, cinco directoras consolidan una presencia que ya no puede ignorarse en Europa.\n\nTatiana Huezo presenta en San Sebastián su tercer largometraje, una coproducción con Dinamarca rodada en Oaxaca. Lila Avilés regresa después del éxito de Tótem con un proyecto documental sobre las mujeres que sostienen los mercados de la Ciudad de México. Fernanda Valadez, cuya Sin señas particulares recorrió treinta festivales, lleva ahora su nueva película directamente a Cannes.\n\nEn Madrid, la programación de Cineteca en Casa de México estrena este mes un ciclo dedicado al Nuevo Cine Mexicano: ocho películas, cuatro directoras, cero condescendencia. No son joyas del pasado ni rareza etnográfica. Son obras del presente que hablan sobre migración, cuerpo y poder con una lucidez que el cine europeo todavía está aprendiendo.\n\nEl ciclo también incluye una conversación pública con la productora Daniela Schneider, que ha acompañado dos de las películas seleccionadas desde su desarrollo. La entrada es libre.",
    "author": "Sofía Leal Noriega",
    "institution": "XICO Madrid",
    "imageKey": "cine-film",
    "readTime": "05 MIN",
    "accentColor": "cobalt",
    "date": "Marzo 2026",
    "type": "Cine",
    "featured": false
  },
  {
    "id": "art-023",
    "slug": "tatiana-huezo-dolor-que-no-prescribe",
    "pillar": "cultura",
    "subcategory": "Cine",
    "category": "Documental",
    "tag": "Cine",
    "title": "Tatiana Huezo y el dolor que no prescribe",
    "subtitle": "Con tres largometrajes, ya es la directora de cine documental más importante de México. Su nuevo trabajo llega a San Sebastián con una coproducción danesa rodada en Oaxaca.",
    "body": "Tatiana Huezo hace películas sobre cosas que México prefiere no ver. El crimen organizado en Tempestad. Los años perdidos en Noche de fuego. El dolor colectivo que no tiene nombre oficial.\n\nSu tercer largometraje, aún sin título definitivo, se rodó durante dieciocho meses en la Sierra Juárez de Oaxaca. Es una coproducción con el Instituto Danés de Cine, un dato que dice mucho sobre dónde está dispuesto a financiarse el cine más valiente que se hace en México: fuera de México.\n\nLa película sigue a tres mujeres de diferentes generaciones en un pueblo que ha sido abandonado por la mitad de sus habitantes. No es una película sobre la migración: es una película sobre lo que queda. Sobre los que se quedan. Sobre cómo se sostiene una comunidad cuando la mitad de sus miembros están en otro continente.\n\n\"El documental no es un género menor. Es el género más honesto que existe, porque no puede esconderse detrás de la ficción cuando miente.\"\n\nLa proyección en Casa de México será seguida de una conversación con la directora vía videoconferencia desde Ciudad de México.",
    "author": "Rodrigo Pacheco Reyes",
    "institution": "XICO Madrid",
    "imageKey": "cine-rodaje",
    "readTime": "06 MIN",
    "accentColor": "primary",
    "date": "Septiembre 2026",
    "type": "Cine",
    "featured": false
  },
  {
    "id": "art-024",
    "slug": "lila-aviles-el-presente-es-el-archivo",
    "pillar": "cultura",
    "subcategory": "Cine",
    "category": "Nuevo Cine Mexicano",
    "tag": "Cine",
    "title": "Lila Avilés: el presente es el archivo",
    "subtitle": "Después del éxito de Tótem en la Berlinale, la directora presenta su nuevo documental sobre las mujeres que sostienen los mercados de la Ciudad de México.",
    "body": "Cuando Tótem se estrenó en la Berlinale de 2023, Lila Avilés ya tenía en mente su siguiente proyecto. No otro drama íntimo sobre una familia. Algo más grande, más ruidoso, más colectivo: los mercados de la Ciudad de México.\n\nDurante dos años filmó en el Mercado de Jamaica, el Mercado de la Merced y el Mercado de Artesanías de Tepito. Sus cámaras siguieron a treinta y dos mujeres que empiezan a trabajar antes de que amanezca y terminan cuando ya no hay luz. Mujeres que son el archivo vivo de una ciudad que se transforma sin memoria.\n\nEl resultado es un documental de dos horas sin narración en off, sin entrevistas a cámara, sin música incidental. Solo las voces, los movimientos y las transacciones de un espacio que es al mismo tiempo mercado, comunidad, historia y caos.\n\n\"Los mercados mexicanos son el lugar donde más cosas pasan al mismo tiempo. Son la versión acelerada de lo que es México: diverso, contradictorio, generoso y brutal.\"\n\nLa película tendrá su estreno europeo en Madrid, en un ciclo especial en colaboración con Casa de México y la Cineteca Nacional.",
    "author": "Valentina Cruz Morales",
    "institution": "XICO Madrid",
    "imageKey": "cine-sala",
    "readTime": "07 MIN",
    "accentColor": "cobalt",
    "date": "Junio 2026",
    "type": "Cine",
    "featured": false
  },
  {
    "id": "art-012",
    "slug": "voces-escena-volpi-rivera",
    "pillar": "cultura",
    "subcategory": "Literatura",
    "category": "Artes Escénicas",
    "tag": "Teatro",
    "title": "Las voces que no callan",
    "subtitle": "Jorge Volpi y Cristina Rivera Garza llevan la narrativa mexicana más contemporánea a los escenarios de Madrid.",
    "body": "Hay algo que el teatro puede hacer que la novela no puede: obligarte a estar presente. Jorge Volpi y Cristina Rivera Garza lo saben. Y por eso sus propuestas escénicas en Casa de México no fueron adaptaciones: fueron actos de pensamiento en tiempo real.\n\nVolpi trajo una pieza sobre la memoria histórica y el presente latinoamericano. Rivera Garza —Premio Pulitzer 2024 por la versión en inglés de El invencible verano de Liliana— propuso algo más difícil de clasificar: un texto que se leía, se escuchaba y se veía al mismo tiempo. Un objeto literario que encontró su forma definitiva en el escenario.\n\nLa programación de artes escénicas de 2025 fue la más ambiciosa en la historia de Casa de México. Más de 40 funciones. Más de 3,500 espectadores. Una lista de creadoras y creadores que incluía también al Ensamble Folclórico Mexicano y pastorelas coordinadas por Leopoldo Falcón.\n\n\"Cristina Rivera Garza convierte el escenario en un lugar donde leer es también mirar.\" — Crítica literaria en La Lectura\n\nLa literatura mexicana más contemporánea no pide perdón por su complejidad. Y Madrid, cuando se le da la oportunidad, la recibe con curiosidad genuina.",
    "author": "Diego Restrepo Arévalo",
    "institution": "Casa de México",
    "imageKey": "culture",
    "readTime": "06 MIN",
    "accentColor": "cobalt",
    "date": "2025",
    "type": "Literatura",
    "featured": false
  },
  {
    "id": "art-025",
    "slug": "natalia-toledo-limite-de-dos-lenguas",
    "pillar": "cultura",
    "subcategory": "Literatura",
    "category": "Poesía",
    "tag": "Literatura",
    "title": "Natalia Toledo: escribir en el límite de dos lenguas",
    "subtitle": "La poeta zapoteca de Juchitán es la voz más singular de la poesía mexicana contemporánea. Su obra se traduce ahora al catalán, al vasco y al galés.",
    "body": "Natalia Toledo escribe en dos idiomas que no se parecen en nada. El zapoteco de Juchitán —su lengua primera, la que aprendió antes que el español— y el español de México, que es también una lengua conquistada y luego conquistada de vuelta.\n\nSus poemas no son traducibles en el sentido habitual. No porque sean crípticos, sino porque contienen sonidos que no existen en otras lenguas. Cuando dice en zapoteco la palabra que significa \"la luz de la tarde sobre el río justo antes de que oscurezca\", ninguna traducción puede capturar exactamente eso.\n\nEn Madrid, su lectura en Casa de México fue uno de los eventos literarios más comentados del año. El público escuchó poemas en zapoteco sin entender una sola palabra. Y los entendió de todas formas.\n\n\"Escribo en zapoteco para no olvidar. Escribo en español para que el mundo pueda entrar. Pero lo más interesante está siempre en el umbral entre las dos lenguas. Ahí vivo yo.\"\n\nLas traducciones al catalán fueron realizadas por la poeta Maria Cabeza de Vaca, y las versiones al vasco por Bernardo Atxaga. El galés lo hizo un estudiante de poesía comparada en Cardiff que leyó sus poemas por accidente y no pudo parar.",
    "author": "Isabel Morales Vega",
    "institution": "XICO Madrid",
    "imageKey": "literatura-escritura",
    "readTime": "07 MIN",
    "accentColor": "emerald",
    "date": "Abril 2026",
    "type": "Literatura",
    "featured": false
  },
  {
    "id": "art-026",
    "slug": "narrativa-mexicana-que-europa-lee",
    "pillar": "cultura",
    "subcategory": "Literatura",
    "category": "Literatura Contemporánea",
    "tag": "Literatura",
    "title": "La narrativa mexicana que Europa está aprendiendo a leer",
    "subtitle": "Más allá de Rulfo: seis voces de la literatura mexicana contemporánea que se traducen al alemán, al francés y al italiano este año.",
    "body": "Durante décadas, la literatura mexicana que llegaba a Europa llegaba tarde. Primero Rulfo, después Fuentes, eventualmente Paz. Todos hombres, todos del siglo XX, todos con un barniz de exotismo prehispánico que las editoriales europeas encontraban vendible.\n\nAlgo está cambiando. Las editoriales alemanas, francesas e italianas están apostando por una nueva generación de autoras mexicanas que no les ofrecen exotismo: les ofrecen literatura.\n\nValeria Luiselli, cuya obra ya se publica en treinta idiomas. Fernanda Melchor, cuya Temporada de huracanes fue finalista del International Booker Prize. Yuri Herrera, cuya trilogía sobre la frontera norte se ha convertido en texto de referencia en los programas de literatura comparada de Oxford y la Sorbona. Emiliano Monge, cuyas novelas sobre violencia y lenguaje están siendo estudiadas en los mejores programas de escritura creativa de Europa.\n\nY las más jóvenes: Daniela Tarazona, Brenda Lozano, Andrea Chapela. Escritoras que trabajan con la ciencia ficción, el terror y el ensayo literario de una manera que no tiene equivalente en la literatura española contemporánea.\n\nLa literatura mexicana ya no necesita que Europa la descubra. Solo necesita que Europa tenga la honestidad de reconocer que llegó tarde.",
    "author": "Diego Restrepo Arévalo",
    "institution": "XICO Madrid",
    "imageKey": "literatura-libros",
    "readTime": "08 MIN",
    "accentColor": "primary",
    "date": "Febrero 2026",
    "type": "Literatura",
    "featured": false
  },
  {
    "id": "art-011",
    "slug": "mexicouture-moda-contemporanea",
    "pillar": "cultura",
    "subcategory": "Moda",
    "category": "Diseño de Moda",
    "tag": "Moda",
    "title": "Mexicouture",
    "subtitle": "Denisse Kuri, Concepción Orvañanos y Arizbeth Fierro llevan el diseño mexicano contemporáneo al corazón del ecosistema creativo de Madrid.",
    "body": "Tres diseñadoras mexicanas. Una ciudad europea que empieza a entender que la moda también puede ser política cultural. El Programa Mexicouture nació para llevar el diseño mexicano contemporáneo al ecosistema creativo español sin necesidad de explicarlo como curiosidad folclórica.\n\nDenisse Kuri trabaja en la intersección entre artesanía y arquitectura textil. Sus piezas no son ropa; son proposiciones formales. Concepción Orvañanos lleva el teñido natural a la haute couture: índigo de Oaxaca, cochinilla de Tlaxcala, añil de Chiapas. Arizbeth Fierro diseña para el cuerpo que se mueve, que trabaja, que existe en el espacio urbano.\n\nLas tres realizaron una estancia en Madrid dentro del marco del Programa de Becas. No vinieron a aprender de España. Vinieron a mostrar lo que México sabe hacer y aún no se ha visto aquí.\n\n\"La moda mexicana no necesita pedir permiso. Necesita espacio. Y ese espacio empieza a existir.\" — Denisse Kuri\n\nEl Programa Mexicouture es un experimento deliberado: construir un puente entre la artesanía mexicana de alta calidad y las industrias creativas europeas. No a través del exotismo, sino a través del oficio.",
    "author": "Isabel Morales Vega",
    "institution": "Casa de México",
    "imageKey": "moda-textil",
    "readTime": "05 MIN",
    "accentColor": "magenta",
    "date": "2025",
    "type": "Moda",
    "featured": false
  },
  {
    "id": "art-027",
    "slug": "indigo-cochinilla-anil",
    "pillar": "cultura",
    "subcategory": "Moda",
    "category": "Tintes Naturales",
    "tag": "Moda",
    "title": "Índigo, cochinilla, añil: el color que viene de la tierra",
    "subtitle": "Tres tintoreras naturales de Oaxaca radicadas en Madrid explican por qué sus colores no se pueden reproducir en laboratorio y por qué eso importa.",
    "body": "El azul índigo de Oaxaca tarda tres semanas en desarrollarse. El rojo cochinilla requiere 70,000 insectos secos para producir medio kilo de tinte. El añil de Chiapas tiene un olor que los tintoreros describen como \"lluvia en tierra de barro\" y que ningún proceso industrial ha podido sintetizar.\n\nEstas tres mujeres —Xóchitl Méndez, Lucía de la Cruz y Amparo Jiménez— llegaron a Madrid en los últimos cinco años. Las tres son tintoreras naturales formadas en la tradición zapoteca e ikojts de Oaxaca. Las tres han encontrado en Madrid algo que no esperaban: curiosidad.\n\nLos diseñadores de moda sostenible de España —y hay cada vez más— están buscando exactamente lo que ellas saben hacer: colores que no se marchitan, técnicas que tienen siglos de depuración y materiales que no contaminan ríos ni pulmones.\n\n\"El problema de la industria de la moda no es estético. Es ético. Y la solución más antigua que existe es también la más hermosa.\"\n\nSu taller en el barrio de Carabanchel recibe cada mes a diseñadores de toda Europa que quieren aprender. Algunas semanas también recibe a niñas de colegios locales que aprenden a teñir lana con cebolla y granada. Eso, dicen las tres, es lo que más les importa.",
    "author": "Fernanda Castillo Ortega",
    "institution": "XICO Madrid",
    "imageKey": "tela-colores",
    "readTime": "06 MIN",
    "accentColor": "cobalt",
    "date": "Enero 2026",
    "type": "Moda",
    "featured": false
  },
  {
    "id": "art-028",
    "slug": "el-tejido-como-manifiesto",
    "pillar": "cultura",
    "subcategory": "Moda",
    "category": "Diseño Contemporáneo",
    "tag": "Moda",
    "title": "El tejido como manifiesto",
    "subtitle": "Una nueva generación de diseñadoras mexicanas demuestra que el huipil puede coexistir con el streetwear. Que la moda también puede ser política.",
    "body": "No hay nada más contemporáneo que un huipil bien cortado. Eso es lo que dice Xochiquetzal Domínguez, diseñadora de 29 años nacida en Oaxaca y radicada en Madrid desde 2022. Y lo dice mientras muestra un huipil de algodón orgánico con bordado zapoteca que ella misma diseñó junto con artesanas de Tehuantepec.\n\nLa nueva generación del diseño mexicano no siente contradicción entre lo tradicional y lo contemporáneo. Para ellas —y son casi todas ellas— el problema no es cómo modernizar la artesanía. El problema es cómo hacer que la industria de la moda respete lo que la artesanía ya sabe.\n\nLas cuatro diseñadoras que comparten este espacio en Madrid —Xochiquetzal, Abril Torres, Marina Rincón y Danae Ojeda— tienen en común algo más que la procedencia. Tienen en común el rechazo a la moda rápida. El rechazo a fabricar en Bangladesh lo que se puede fabricar en Oaxaca.\n\n\"El lujo verdadero no es lo que cuesta más. Es lo que no se puede fabricar dos veces igual.\"\n\nSu primera colección colectiva se presentó en el Festival de Moda Sostenible de Madrid en enero de 2026. Vendieron todo en dos horas.",
    "author": "Valentina Cruz Morales",
    "institution": "XICO Madrid",
    "imageKey": "moda-runway",
    "readTime": "05 MIN",
    "accentColor": "magenta",
    "date": "Enero 2026",
    "type": "Moda",
    "featured": false
  },
  {
    "id": "art-006",
    "slug": "altar-de-muertos-octava-edicion",
    "pillar": "mexico-ahora",
    "subcategory": "Tradición",
    "category": "Tradición y Arte Popular",
    "tag": "Día de Muertos",
    "title": "El cabaret de los que ya no están",
    "subtitle": "Guillermo González diseñó la octava edición del Altar de Muertos: doce catrinas que bailan en terciopelo, esferas de vidrio soplado y lentejuelas.",
    "body": "El Altar de Muertos de Fundación Casa de México es ya una referencia en el calendario cultural español. Con más de 100,000 visitantes en su octava edición, supera cualquier cifra previa y confirma que México tiene algo que España quiere vivir, no solo ver.\n\nGuillermo González —el mismo creador que lleva ocho años imaginando altares distintos— concibió esta vez el cabaret de los años cuarenta y cincuenta en la Ciudad de México. El cabaret El Recuerdo. Doce catrinas de tamaño natural que bailan y continúan divirtiéndose después de la muerte.\n\nTerciopelo. Esferas de vidrio soplado. Lentejuelas. Cada material elegido con criterio: no para hacer bonito, sino para hacer verdadero. El Día de Muertos tiende un puente simbólico entre el mundo de los vivos y los muertos. Sabores, olores, colores: cada elemento en el altar posee un significado profundo íntimamente relacionado con los sentidos.\n\nA lo largo de la Casa, una selección de la colección de arte popular acompañó el altar: piezas que recuerdan que la muerte en México no es el fin del mundo. Es parte de él.",
    "author": "Adriana Vilchis Nava",
    "institution": "Casa de México",
    "imageKey": "dia-de-muertos",
    "readTime": "04 MIN",
    "accentColor": "ochre",
    "date": "Noviembre 2025",
    "type": "Tradición",
    "featured": true
  },
  {
    "id": "art-010",
    "slug": "primavera-mariposas-fachada",
    "pillar": "mexico-ahora",
    "subcategory": "Arte Urbano",
    "category": "Intervención Urbana",
    "tag": "Arte e Identidad",
    "title": "30,000 flores para la primavera",
    "subtitle": "Cristina Faesler y Mateo Holmes cubrieron la fachada de Casa de México con diecisiete mariposas elaboradas con flores vivas.",
    "body": "México alberga el 9% de las especies de mariposas conocidas en el planeta. Un dato que nos recuerda la rica biodiversidad del país. Y para celebrarlo, Cristina Faesler y el arquitecto Mateo Holmes presentaron en nuestra fachada diecisiete mariposas de gran tamaño elaboradas con flores vivas.\n\nLa mariposa azufre. El morpho azul. La mariposa cometa. La baronia mexicana. La mariposa limón. Y por supuesto, la emblemática monarca, viajera incansable que cruza América del Norte. A su alrededor, más de 30,000 flores naturales recrearon la riqueza de los árboles florales mexicanos: la delicada flor de la pasión, la vainilla, la flor de mayo y el vibrante tabachín.\n\nEn los pasillos de las tres plantas del edificio se exhibió Flora y fauna por manos mexicanas: cuarenta y tres piezas entre nahuales tallados en madera de copal de Oaxaca, baúles y bateas de Guerrero y cerámica de Chiapas, Jalisco, Michoacán y Veracruz.\n\nLa primavera de México llegó a Madrid en forma de arte efímero. Las flores se secan. Los colores permanecen.",
    "author": "Fernanda Castillo Ortega",
    "institution": "Casa de México",
    "imageKey": "artesania-mexicana",
    "readTime": "04 MIN",
    "accentColor": "emerald",
    "date": "Marzo 2025",
    "type": "Arte Urbano",
    "featured": false
  },
  {
    "id": "art-013",
    "slug": "maiz-que-madrid-no-conoce",
    "pillar": "mexico-ahora",
    "subcategory": "Gastronomía",
    "category": "México Ahora",
    "tag": "Gastronomía",
    "title": "El maíz que Madrid no conoce",
    "subtitle": "La nixtamalización está transformando la escena gastronómica de Madrid. De la tortilla artesanal a la alta cocina: una revolución silenciosa.",
    "body": "Madrid lleva años enamorándose de la cocina mexicana. Pero hay un ingrediente que la ciudad todavía no comprende del todo: el maíz. No el maíz de la lata. El maíz vivo, diverso, político. El maíz que es civilización.\n\nLa nixtamalización —el proceso de cocer el maíz con cal para liberar sus nutrientes y transformar su textura— llegó a Madrid en los últimos tres años de la mano de chefs mexicanos que decidieron no simplificar su cocina para el paladar europeo. Tortillas azules de maíz criollo. Tlayudas de maíz bolita de Oaxaca. Tamales de maíz cacahuazintle del Estado de México.\n\nEl chef Roberto Ruiz fue el primero en llevar la tortilla de maíz nixtamalizado a la alta cocina española. Hoy, una docena de restaurantes certificados con el Sello Copil trabajan con maíces criollos importados directamente de productores en Oaxaca, Jalisco y Puebla.\n\n\"Servir una tortilla industrial es mentir sobre México. Servir una tortilla de maíz criollo es un acto político.\" — Chef en conversación con XICO\n\nLa Xalte de Colima —flor de sal artesanal— encontró su lugar en la coctelería de autor. La vainilla de Papantla perfuma postres en restaurantes con estrella Michelin. Y el mole negro de Oaxaca es ahora tema de conversación en las mejores mesas de la capital española.",
    "author": "Alejandra Mota Díaz",
    "institution": "XICO Madrid",
    "imageKey": "cocina-alta",
    "readTime": "05 MIN",
    "accentColor": "emerald",
    "date": "Marzo 2026",
    "type": "Gastronomía",
    "featured": true
  },
  {
    "id": "art-014",
    "slug": "cinco-artistas-que-madrid-deberia-conocer",
    "pillar": "mexico-ahora",
    "subcategory": "Arte Contemporáneo",
    "category": "México Ahora",
    "tag": "Arte Contemporáneo",
    "title": "Cinco artistas que Madrid debería conocer",
    "subtitle": "Una nueva generación de creadoras mexicanas instala su práctica en España. Nombres para seguir ahora.",
    "body": "No vinieron a quedarse para siempre. Vinieron a trabajar. Y en ese proceso, sin buscarlo, se convirtieron en parte del tejido cultural de Madrid. Cinco creadoras mexicanas cuya práctica merece atención inmediata.\n\nFernanda Laguna trabaja la cerámica como si fuera escritura: piezas que cuentan historias sin necesitar un título. Su estudio en Lavapiés es parada obligada para quien quiera entender cómo el arte popular mexicano se transforma al contacto con Europa.\n\nMariana Castillo Deball ya es conocida en los circuitos de arte contemporáneo internacional —fue seleccionada para representar a México en la Bienal de Venecia—, pero su trabajo merece una lectura más lenta, más atenta.\n\nYolanda Gutiérrez lleva años construyendo instalaciones con materiales naturales que dialogan con la ecología, la identidad y el tiempo. Su exposición en el Centro de Arte Dos de Mayo fue una de las más comentadas del año.\n\nPaula Flores, diseñadora gráfica que trabaja entre Ciudad de México y Madrid, ha creado identidades visuales para algunas de las marcas culturales más interesantes de ambas ciudades. Y Sofía Táboas, cuya propuesta escultórica sobre los materiales industriales sigue siendo una de las más rigurosas de su generación.",
    "author": "Valeria Montoya Ríos",
    "institution": "XICO Madrid",
    "imageKey": "arte-contemporaneo",
    "readTime": "06 MIN",
    "accentColor": "magenta",
    "date": "Marzo 2026",
    "type": "Arte Contemporáneo",
    "featured": false
  },
  {
    "id": "art-015",
    "slug": "la-temporada-que-se-abre",
    "pillar": "mexico-ahora",
    "subcategory": "Agenda",
    "category": "Agenda Cultural",
    "tag": "Agenda",
    "title": "La temporada que se abre",
    "subtitle": "PHotoESPAÑA 2026, el nuevo ciclo de Jumex en Europa y la agenda de Casa de México: lo que no te puedes perder en Madrid este mes.",
    "body": "Marzo llega cargado. Si vives en Madrid y te importa la cultura mexicana contemporánea, este mes tienes excusas de sobra para salir.\n\nPHotoESPAÑA 2026 arranca su convocatoria con dos artistas mexicanas en las secciones oficiales: Flor Garduño y Daniela Edburg. La primera trae un trabajo sobre el cuerpo femenino y la naturaleza que nunca ha tenido una muestra retrospectiva en Europa. La segunda expone por primera vez en el circuito de fotoperiodismo de autor.\n\nLa Colección Jumex confirma que su nuevo programa de exposiciones itinerantes por Europa pasará por Madrid en mayo. El anticipo —tres piezas de Francis Alÿs y una instalación de Abraham Cruzvillegas— se puede ver ya en la galería del Paseo de Recoletos.\n\nCasa de México abre su nueva temporada con Frontera/Border: una exposición fotográfica colectiva sobre la experiencia migratoria entre México y España. Doce fotógrafas. Doce miradas. Una sola pregunta: ¿qué se pierde y qué se gana cuando cruzas un océano?\n\nY si buscas algo para este fin de semana: la cata de mezcales artesanales en colaboración con México Enlaza vuelve el próximo sábado. Entrada libre con inscripción previa.",
    "author": "Sofía Leal Noriega",
    "institution": "XICO Madrid",
    "imageKey": "gastronomia-fina",
    "readTime": "04 MIN",
    "accentColor": "cobalt",
    "date": "Marzo 2026",
    "type": "Agenda",
    "featured": true
  }
];

export default articles;
