const events = [
  {
    id: "ev-001",
    title: "Cata de Mezcales Artesanales · Mexico Enlaza",
    starts_at: "2026-05-15T20:00:00.000Z",
    venue_name: "Casa de México en España · Serrano 46",
    description: "Segunda edición de la cata mensual de Mexico Enlaza. Doce mezcales artesanales de Oaxaca, Guerrero y Durango presentados por sus productores. Maridaje con botanas tradicionales de la región. Cupos limitados a 60 personas.",
    category: "gastronomia",
    price: "€15",
  },
  {
    id: "ev-002",
    title: "Coloquio: Literatura Mexicana en Europa Hoy",
    starts_at: "2026-05-22T19:30:00.000Z",
    venue_name: "Casa de México en España · Serrano 46",
    description: "Encuentro con tres editores europeos que han apostado por la literatura mexicana contemporánea: Anagrama, Periférica y Sexto Piso. Hablarán sobre qué leen, qué rechazan y por qué la narrativa mexicana está cambiando el catálogo europeo. Moderado por Diego Restrepo.",
    category: "literatura",
    price: "Gratuito",
  },
  {
    id: "ev-003",
    title: "Taller de Tintes Naturales Oaxaqueños",
    starts_at: "2026-06-05T17:00:00.000Z",
    venue_name: "Taller Tintes Naturales · Carabanchel Alto 14",
    description: "Taller de tres horas con Xóchitl Méndez y Lucía de la Cruz. Los participantes aprenderán el proceso completo del teñido con cochinilla e índigo: preparación de la fibra, baño de tinte y fijación natural. Cada participante se lleva su pieza. Materiales incluidos.",
    category: "artes-visuales",
    price: "€35",
  },
  {
    id: "ev-004",
    title: "Inauguración PHotoESPAÑA · Flor Garduño",
    starts_at: "2026-06-12T20:00:00.000Z",
    venue_name: "Círculo de Bellas Artes · Calle de Alcalá 42",
    description: "Inauguración oficial de la primera retrospectiva europea de Flor Garduño. Ciento veinte fotografías en blanco y negro de cuatro décadas de trabajo. La artista estará presente. Acceso libre hasta completar aforo. La exposición permanece abierta hasta el 30 de agosto.",
    category: "artes-visuales",
    price: "Gratuito",
  },
  {
    id: "ev-005",
    title: "Ciclo Nuevo Cine Mexicano · Lila Avilés",
    starts_at: "2026-06-18T20:30:00.000Z",
    venue_name: "Casa de México en España · Serrano 46",
    description: "Proyección de Tótem (2023) y presentación del nuevo documental de Lila Avilés sobre los mercados de la Ciudad de México. La directora participará en un coloquio posterior vía videoconferencia desde Ciudad de México. Subtítulos en español.",
    category: "artes-visuales",
    price: "€5",
  },
  {
    id: "ev-006",
    title: "Lectura de Poesía · Natalia Toledo",
    starts_at: "2026-07-03T20:00:00.000Z",
    venue_name: "Casa de México en España · Serrano 46",
    description: "La poeta zapoteca de Juchitán lee en zapoteco y español durante noventa minutos. Presentación de sus traducciones al catalán, vasco y galés. Conversación con la traductora catalana Maria Cabeza de Vaca. Sin interpretación: la escucha directa del zapoteco es parte de la experiencia.",
    category: "literatura",
    price: "Gratuito",
  },
  {
    id: "ev-007",
    title: "Chefmex Gourmet 2026",
    starts_at: "2026-09-18T12:00:00.000Z",
    venue_name: "IFEMA · Pabellón 14",
    description: "Tercera edición del encuentro profesional de gastronomía mexicana en España. Más de 700 profesionales del sector: chefs, distribuidores, productores y críticos gastronómicos. Jornada de ponencias, talleres y catas. Acreditación profesional o entrada general disponible.",
    category: "gastronomia",
    price: "€45",
  },
  {
    id: "ev-008",
    title: "Noche de Museos · Arte Mexicano Contemporáneo",
    starts_at: "2026-10-17T20:00:00.000Z",
    venue_name: "Casa de México en España · Serrano 46",
    description: "Apertura especial nocturna con visita guiada a la colección permanente de arte popular y a la exposición temporal Frontera/Border. Actuación en vivo del Ensamble Folclórico Mexicano a las 21:30. Entrada libre hasta completar aforo.",
    category: "artes-visuales",
    price: "Gratuito",
  },
];

export default events;
