import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import articlesRouter from "./articles.js";
import savedRouter from "./saved.js";
import profileRouter from "./profile.js";
import momentosRouter from "./momentos.js";
import eventsRouter from "./events.js";
import spotsRouter from "./spots.js";
import rutaRouter from "./ruta.js";
import edicionRouter from "./edicion.js";
import ttsRouter from "./tts.js";
import despachoRouter from "./despacho.js";
import companionRouter from "./companion.js";
import personalizationRouter from "./personalization.js";
import editorLettersRouter from "./editor-letters.js";
import rumbosRouter from "./rumbos.js";
import rutaStopsRouter from "./ruta-stops.js";
import sellosRumboRouter from "./sellos-rumbo.js";
import rutaStopNotesRouter from "./ruta-stop-notes.js";
import madridPulseRouter from "./madrid-pulse.js";
import emotionalEventsRouter from "./emotional-events.js";

const router: IRouter = Router();

router.use("/health", healthRouter);
router.use("/articles", articlesRouter);
router.use("/momentos", momentosRouter);
router.use("/events", eventsRouter);
router.use("/spots", spotsRouter);
router.use("/ruta", rutaRouter);
router.use("/edicion", edicionRouter);
router.use("/tts", ttsRouter);
router.use("/saved", savedRouter);
router.use("/profile", profileRouter);
router.use("/despacho", despachoRouter);
router.use("/companion", companionRouter);
router.use("/personalization", personalizationRouter);
router.use("/editor-letters", editorLettersRouter);
router.use("/rumbos", rumbosRouter);
router.use("/ruta-stops", rutaStopsRouter);
router.use("/sellos-rumbo", sellosRumboRouter);
router.use("/ruta-stop-notes", rutaStopNotesRouter);
router.use("/madrid-pulse", madridPulseRouter);
router.use("/emotional-events", emotionalEventsRouter);

export default router;