const momentos = [
  {
    id: "m-001",
    headline: "Retrospectiva Iturbide bate récord de asistencia en Casa de México",
    caption: "Más de 12,000 visitantes en el primer mes. La exposición permanece abierta hasta el 30 de junio.",
    category: "fotografía",
    accent_color: "magenta",
    image_url: null,
  },
  {
    id: "m-002",
    headline: "Tres nuevos restaurantes obtienen el Sello Copil en mayo",
    caption: "Barro, Mezcalito y La Palapa se suman a los cerca de cien establecimientos certificados en Madrid.",
    category: "gastronomía",
    accent_color: "ochre",
    image_url: null,
  },
  {
    id: "m-003",
    headline: "PHotoESPAÑA 2026 confirma a Flor Garduño como artista protagonista",
    caption: "Primera retrospectiva europea de la fotógrafa oaxaqueña. Inauguración el 12 de junio en el Círculo de Bellas Artes.",
    category: "fotografía",
    accent_color: "magenta",
    image_url: null,
  },
  {
    id: "m-004",
    headline: "Lista de espera para la cata de mezcales: 200 personas inscritas",
    caption: "La cata de Mexico Enlaza del próximo 15 de mayo se llena en 48 horas. Hay lista de espera abierta.",
    category: "gastronomía",
    accent_color: "ochre",
    image_url: null,
  },
  {
    id: "m-005",
    headline: "Natalia Toledo lee en Casa de México: todas las sillas ocupadas",
    caption: "La poeta zapoteca leyó en zapoteco y español durante 90 minutos. El silencio en la sala fue absoluto.",
    category: "literatura",
    accent_color: "emerald",
    image_url: null,
  },
  {
    id: "m-006",
    headline: "La Colección Jumex trae tres Francis Alÿs a Madrid en mayo",
    caption: "Anticipo del programa de exposiciones itinerantes. Las piezas ya están colgadas en la galería de Paseo de Recoletos.",
    category: "artes visuales",
    accent_color: "cobalt",
    image_url: null,
  },
  {
    id: "m-007",
    headline: "Victoria Riva Palacio actúa en el Reina Sofía el 20 de junio",
    caption: "La coreógrafa mexicana lleva Coreograf-IA al museo más importante de arte contemporáneo de España.",
    category: "danza",
    accent_color: "cobalt",
    image_url: null,
  },
  {
    id: "m-008",
    headline: "El maíz azul nixtamalizado llega a cinco nuevos restaurantes de Madrid",
    caption: "Productores de Oaxaca envían partidas directas. La tortilla de maíz criollo empieza a ser parte del paisaje gastronómico de la capital.",
    category: "gastronomía",
    accent_color: "ochre",
    image_url: null,
  },
  {
    id: "m-009",
    headline: "Fernanda Melchor: su segunda novela se publica en España en septiembre",
    caption: "Editorial Penguin Random House confirma la traducción de Páradais. Presentación en la Casa del Libro en octubre.",
    category: "literatura",
    accent_color: "emerald",
    image_url: null,
  },
  {
    id: "m-010",
    headline: "Casa de México abre Frontera/Border el 10 de junio",
    caption: "Doce fotógrafas, doce miradas sobre la experiencia migratoria entre México y España. Entrada libre.",
    category: "fotografía",
    accent_color: "magenta",
    image_url: null,
  },
];

export default momentos;
