const ruta = {
  id: "ruta-001",
  title: "La Ruta del Mezcal",
  subtitle: "Cinco paradas por el mejor mezcal artesanal de Madrid. Desde Serrano hasta Malasaña: una tarde que empieza con cultura y termina con humo de agave.",
  month: "Mayo",
  is_active: true,
  stops: [
    {
      id: "stop-001",
      ruta_id: "ruta-001",
      order_num: 1,
      name: "Casa de México en España",
      address: "Calle de Serrano, 46",
      description: "Empieza en la institución. La colección de arte popular mexicano incluye piezas de maestros artesanos de Oaxaca, los mismos estados que producen el mejor mezcal. Visita la tienda Hecho a Mano antes de salir.",
      category: "cultural",
      accent_color: "magenta",
      time_suggestion: "17:00",
      distance_to_next: "2.1 km en metro o 25 min a pie",
    },
    {
      id: "stop-002",
      ruta_id: "ruta-001",
      order_num: 2,
      name: "Punto MX",
      address: "Calle del Doctor Castelo, 26",
      description: "Roberto Ruiz tiene la carta de mezcales más respetada de Madrid. Pide el ensamble de Durango y las tostadas de aguacate con chapulín para empezar. Son dos estrellas Michelin, pero el mezcal se toma sin protocolo.",
      category: "restaurant",
      accent_color: "ochre",
      time_suggestion: "18:00",
      distance_to_next: "1.4 km en metro o 18 min a pie",
    },
    {
      id: "stop-003",
      ruta_id: "ruta-001",
      order_num: 3,
      name: "Barracuda MX",
      address: "Calle de las Infantas, 27",
      description: "La coctelería de mezcal más creativa de la ciudad. Pide el Mezcal Negroni con bitters de chocolate oaxaqueño o el Spicy Margarita de habanero. El bartender conoce cada destilería de su carta de memoria.",
      category: "bar",
      accent_color: "magenta",
      time_suggestion: "19:30",
      distance_to_next: "0.9 km a pie",
    },
    {
      id: "stop-004",
      ruta_id: "ruta-001",
      order_num: 4,
      name: "Corazón de Agave",
      address: "Calle del Amparo, 50",
      description: "La mezcalería de Lavapiés tiene 60 referencias de mezcal artesanal. Aquí el mezcal se bebe solo, en vaso de barro, con una naranja y sal de gusano. Botanas gratis con cada copa. El ambiente es el de una cantina real.",
      category: "bar",
      accent_color: "ochre",
      time_suggestion: "21:00",
      distance_to_next: "1.8 km a pie o en metro",
    },
    {
      id: "stop-005",
      ruta_id: "ruta-001",
      order_num: 5,
      name: "La Tilica Mezcalería",
      address: "Calle de la Palma, 40",
      description: "El cierre perfecto. La Tilica tiene 85 referencias y los jueves trae productores de Oaxaca para catas abiertas. Si llegas un jueves, la noche puede terminar con una lección magistral de un maestro mezcalero. Sin filtros.",
      category: "bar",
      accent_color: "ochre",
      time_suggestion: "22:30",
      distance_to_next: null,
    },
  ],
};

export default ruta;
