const spots = [
  {
    id: "sp-001",
    name: "Punto MX",
    type: "restaurant",
    description: "El primer restaurante mexicano de alta gama en Madrid. Roberto Ruiz reinterpreta la cocina mexicana con tortillas de maíz nixtamalizado, mole negro y mezcales de autor. Dos estrellas Michelin. Sello Copil certificado.",
    address: "Calle del Doctor Castelo, 26",
    neighborhood: "Retiro",
    lat: 40.4183,
    lng: -3.6904,
    is_copil: true,
    accent_color: "ochre",
    tags: ["alta cocina", "mole", "maíz nixtamalizado", "mezcal", "Michelin"],
  },
  {
    id: "sp-002",
    name: "Tepic",
    type: "restaurant",
    description: "Cocina mexicana de mercado en el corazón de Recoletos. Tacos de canasta, tostadas de atún y margaritas de jalapeño. La cocina que mejor explica México sin necesitar traducción. Sello Copil certificado.",
    address: "Calle de la Reina, 3",
    neighborhood: "Recoletos",
    lat: 40.4218,
    lng: -3.6897,
    is_copil: true,
    accent_color: "ochre",
    tags: ["tacos", "cocina de mercado", "margaritas", "casual"],
  },
  {
    id: "sp-003",
    name: "Barracuda MX",
    type: "restaurant",
    description: "El más irreverente de los restaurantes mexicanos de Madrid. Ceviche de habanero, tostadas de pulpo y una carta de mezcales que tiene 40 referencias. En el corazón de Chueca. Sello Copil certificado.",
    address: "Calle de las Infantas, 27",
    neighborhood: "Chueca",
    lat: 40.4202,
    lng: -3.6975,
    is_copil: true,
    accent_color: "magenta",
    tags: ["ceviche", "mezcal", "irreverente", "Chueca", "coctelería"],
  },
  {
    id: "sp-004",
    name: "Corazón de Agave",
    type: "bar",
    description: "Mezcalería y cantina mexicana en Lavapiés. La colección de mezcales artesanales más completa del barrio: 60 referencias de Oaxaca, Guerrero y Durango. Botanas gratuitas con cada copa. Ambiente de barrio real.",
    address: "Calle del Amparo, 50",
    neighborhood: "Lavapiés",
    lat: 40.4079,
    lng: -3.7035,
    is_copil: true,
    accent_color: "ochre",
    tags: ["mezcal", "cantina", "Lavapiés", "artesanal", "botanas"],
  },
  {
    id: "sp-005",
    name: "La Lupita",
    type: "restaurant",
    description: "Cocina popular mexicana con ingredientes de primera. Enchiladas verdes, pozole rojo de domingo y agua de horchata hecha a mano. La taquería de barrio que Madrid necesitaba. Sello Copil certificado.",
    address: "Calle de Fuencarral, 43",
    neighborhood: "Chueca",
    lat: 40.4237,
    lng: -3.6992,
    is_copil: true,
    accent_color: "emerald",
    tags: ["tacos", "enchiladas", "pozole", "popular", "horchata"],
  },
  {
    id: "sp-006",
    name: "Barro",
    type: "restaurant",
    description: "El restaurante más íntimo de la escena mexicana de Madrid. Jorge Muñoz trabaja con productores locales españoles desde una perspectiva mexicana: embutidos con chile, queso manchego con mole, pan de masa madre con mantequilla de epazote.",
    address: "Calle de Almagro, 19",
    neighborhood: "Almagro",
    lat: 40.4302,
    lng: -3.6933,
    is_copil: true,
    accent_color: "cobalt",
    tags: ["fusión", "temporada", "íntimo", "alta cocina", "natural"],
  },
  {
    id: "sp-007",
    name: "Casa de México en España",
    type: "cultural",
    description: "La institución cultural mexicana más importante de Europa. Exposiciones, conciertos, teatro, talleres, conferencias. La colección de arte popular mexicano más completa fuera de México. Sede del programa Sello Copil.",
    address: "Calle de Serrano, 46",
    neighborhood: "Salamanca",
    lat: 40.4259,
    lng: -3.6861,
    is_copil: false,
    accent_color: "magenta",
    tags: ["cultura", "exposiciones", "arte popular", "colecciones", "eventos"],
  },
  {
    id: "sp-008",
    name: "La Tilica Mezcalería",
    type: "bar",
    description: "La mezcalería de referencia de Malasaña. 85 referencias de mezcal artesanal y ensamble. Catas los jueves con productores invitados. Coctelería de autor con ingredientes mexicanos: tamarindo, guayaba, chile de árbol.",
    address: "Calle de la Palma, 40",
    neighborhood: "Malasaña",
    lat: 40.4276,
    lng: -3.7058,
    is_copil: false,
    accent_color: "ochre",
    tags: ["mezcal", "catas", "coctelería", "Malasaña", "artesanal"],
  },
  {
    id: "sp-009",
    name: "El Burladero",
    type: "restaurant",
    description: "Antojería mexicana en el centro histórico. Los mejores tlayudas de Madrid. Masa de maíz negro de Oaxaca, frijoles negros de olla y tasajo importado. Con terraza en una callejuela del barrio de las Letras. Sello Copil certificado.",
    address: "Calle de las Huertas, 52",
    neighborhood: "Barrio de las Letras",
    lat: 40.4142,
    lng: -3.6987,
    is_copil: true,
    accent_color: "ochre",
    tags: ["tlayudas", "oaxaqueño", "antojería", "terraza", "maíz negro"],
  },
  {
    id: "sp-010",
    name: "Taller Tintes Naturales",
    type: "workshop",
    description: "El taller de Xóchitl Méndez, Lucía de la Cruz y Amparo Jiménez en Carabanchel. Tintes naturales de tradición oaxaqueña: índigo, cochinilla, añil. Talleres regulares con diseñadores de moda y visitas escolares. Con cita previa.",
    address: "Calle de Carabanchel Alto, 14",
    neighborhood: "Carabanchel",
    lat: 40.3861,
    lng: -3.7214,
    is_copil: false,
    accent_color: "cobalt",
    tags: ["tintes naturales", "oaxaqueño", "taller", "moda sostenible", "artesanía"],
  },
];

export default spots;
